version: "2"

run:
  timeout: 2m

linters:
  enable:
    - govet         # стандартный анализатор ошибок
    - errcheck      # проверка необработанных ошибок
    - staticcheck   # много полезных проверок (устаревшие функции, ошибки)
    - unused        # поиск неиспользуемых переменных, функций и т.д.

formatters:
  enable:
    - gofmt
    - goimports

output:
  formats:
    tab: {}
    json: {}