run:
  timeout: 2m

linters:
  enable:
    - govet         # стандартный анализатор ошибок
    - errcheck      # проверка необработанных ошибок
    - staticcheck   # много полезных проверок (устаревшие функции, ошибки)
    - gofmt         # проверка форматирования
    - goimports     # порядок и наличие импортов
    - unused        # поиск неиспользуемых переменных, функций и т.д.

output:
  print-issued-lines: true
  print-linter-name: true